# Generated by Django 3.1.7 on 2023-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20230217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=100, null=True),
        ),
    ]
