# Generated by Django 3.1.7 on 2023-02-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20230221_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentlikes',
            old_name='count',
            new_name='count_likes',
        ),
    ]
