# Generated by Django 3.1.7 on 2023-02-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20230221_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcomments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contentlikes',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.RemoveField(
            model_name='contentlikes',
            name='count_likes',
        ),
        migrations.AddField(
            model_name='contentlikes',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
