# Generated by Django 3.1.7 on 2023-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20230222_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
