# Generated by Django 3.1.7 on 2023-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_content_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingPath', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('eof', models.BooleanField()),
            ],
        ),
    ]
